### ISSUE TITLE
 ERROR ReferenceError: fillAddress is not defined

### ISSUE THREAD

**Issue by KooT** [gkoo/hubot-maps#5]
ERROR ReferenceError: fillAddress is not defined ;/

**Comment by neocotic** [comment]
Yea. I'm seeing this too.

**Comment by nhoag** [comment]
See https://github.com/gkoo/hubot-maps/pull/3 for a working patch.

**Comment by technicalpickles** [comment]
A fix for this has been released. You can get the update in an existing hubot install with: npm install --save hubot-maps@0.0.2.
